site_name: Caracal
repo_name: dioptra-io/caracal
repo_url: https://github.com/dioptra-io/caracal
theme:
  name: material
  features:
    - navigation.tabs
  icon:
    logo: material/cat
    repo: fontawesome/brands/github
plugins:
  - search
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - index.md
  - usage.md
  - python.md
  - dev.md
extra:
  social:
    - icon: material/web
      link: http://dioptra.io
    - icon: fontawesome/brands/github
      link: https://github.com/dioptra-io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Dioptra-101576075023596/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/68485078/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DioptraTech
