name: Binaries

on: [ push ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1
        with:
          version: '2.21.0'  # specify Conan 2.x version or omit for latest
          cache_packages: true  # automatically cache Conan packages
      - name: Install dependencies
        run: sudo apt update && sudo apt install --yes build-essential cmake ninja-build
      - name: Install Conan dependencies
        run: conan install . --build=missing
      - name: Configure project
        run: cmake -S . -B build -G Ninja -DWITH_BINARY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
      - name: Build executable
        run: |
          cmake --build build --target caracal-bin
          mv build/caracal build/caracal-linux-amd64
      - uses: actions/upload-artifact@v4.6.2
        with:
          path: build/caracal-linux-amd64

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1
        with:
          version: '2.21.0'
          cache_packages: true
      - name: Install dependencies
        run: brew install cmake ninja
      - name: Install Conan dependencies
        run: conan install . --build=missing
      - name: Configure project
        run: cmake -S . -B build -G Ninja -DWITH_BINARY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
      - name: Build executable
        run: |
          cmake --build build --target caracal-bin
          mv build/caracal build/caracal-macos-amd64
      - uses: actions/upload-artifact@v4.6.2
        with:
          path: build/caracal-macos-amd64

  release:
    needs: [ linux, macos ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.7
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifact/*
