name: CI

on:
  push:
    branches: [ main ]
    paths-ignore: ['**.md']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Build Docker image
        run: |
          docker build --tag debug --target builder .
          docker build --tag caracal .
      - name: Test Docker image
        run: docker run caracal --help
      - name: Run unit tests with coverage
        run: |
          docker run \
            --name debug \
            --env GITHUB_ACTIONS=1 \
            --workdir /tmp/build-debug \
            debug \
            cmake --build . --target coverage --parallel 8
      - name: Upload coverage
        run: |
          docker cp debug:/tmp/build-debug/coverage.xml .
          bash <(curl -s https://codecov.io/bash)
      - name: Copy documentation
        run: docker cp debug:/tmp/build-debug/html html
      - name: Upload documentation
        if: github.event_name == 'push' && success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
