name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: docker-layer-caching-{hash}
          restore-keys: |
            docker-layer-caching-
      - name: Build Docker image
        run: |
          docker build --target builder -t debug .
          docker build -t diamond-miner-prober .
      - name: Test Docker image
        run: docker run diamond-miner-prober --help
      - name: Run unit tests
        run: docker run --name debug -w /tmp/build-debug debug make coverage
      - name: Copy documentation
        run: docker cp debug:/tmp/build-debug/html html
      - name: Upload documentation
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage
        run: |
          docker cp debug:/tmp/build-debug/coverage.xml .
          bash <(curl -s https://codecov.io/bash)
