name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Docker image
        run: |
          docker build --target builder -t debug .
          docker build -t diamond-miner-prober .
      - name: Test Docker image
        run: docker run diamond-miner-prober --help
      - name: Run unit tests
        run: docker run --name debug -w /tmp/build/debug debug make coverage
      - name: Upload coverage
        run: |
          docker cp debug:/tmp/build/debug/coverage.xml .
          bash <(curl -s https://codecov.io/bash)
