name: Docker Hub

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          submodules: true

      - name: Publish to Docker Registry (latest)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dioptraio/caracal
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest

      - name: Publish to Docker Registry (tag)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dioptraio/caracal
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
