name: Documentation
on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install --yes doxygen graphviz
    - name: Build documentation
      run: doxygen
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
