name: Tests

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Docker image
        run: docker build --tag caracal .
      - name: Test Docker image
        run: docker run caracal --help

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: ~/.conan/data
          key: ${{ runner.os }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --yes build-essential cmake gcovr git ninja-build python3-dev python3-pip
          pip3 install conan
      - name: Configure project
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=ON -DWITH_SANITIZER=ON
      - name: Build and run tests
        run: sudo --preserve-env=CI cmake --build build --target coverage
      - uses: codecov/codecov-action@v2
        with:
          directory: build

  macos:
    # bison fails to build on macos-11 on GitHub actions.
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: ~/.conan/data
          key: ${{ runner.os }}
      - name: Install dependencies
        run: brew install cmake conan gcovr ninja
      - name: Configure project
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=ON -DWITH_SANITIZER=ON
      - name: Build and run tests
        run: sudo --preserve-env=CI cmake --build build --target coverage
        env:
          GITHUB_ACTIONS: 1
      - uses: codecov/codecov-action@v2
        with:
          directory: build
